### ISSUE TITLE
where is the probabilities in soba_jax  in spaba.py?

### ISSUE THREAD

**Issue by wanli-19** [SUSTech-Optimization/SPABA#1]
Hi,

I have a question about the implementation of spaba.py. 

Why soba_jax in spaba.py do not use the probability p?

In the paper, SPABA uses the following gradient estimation.
![image](https://github.com/user-attachments/assets/59968cf0-0516-4fc2-acaf-85602dca8aba)
However, in function soba_jax the probability p doesn't exist and the the variables are updated twice (in Line 319-321 and in Line 343-345).  Is there something wrong with my understanding?

**Comment by SUSTech-Optimization** [comment]
Thank you for following our work. Sorry for uploading the test version of the code by mistake. We have made the necessary corrections. If you encounter any further issues, please feel free to contact us.

**Comment by wanli-19** [comment]
Thanks for your response
